version: '3'
services:
  db:

    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "0802"
    ports:
       - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: